# Generated by Django 2.2.6 on 2020-03-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='image',
            field=models.ImageField(default='jobposts/g.jgp', upload_to='jobpost/'),
            preserve_default=False,
        ),
    ]
