# Generated by Django 2.2.6 on 2020-04-01 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_jobposts_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobposts',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, default='2019-04-01 10:23'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='image',
            field=models.ImageField(upload_to='jobposts'),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='job_type',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='jobposts',
            name='salary',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
