# Generated by Django 2.2.6 on 2020-04-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='content',
            field=models.CharField(max_length=1500),
        ),
    ]
