# Generated by Django 2.2.6 on 2020-04-01 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0005_auto_20200401_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resume',
            name='catagory',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='content',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='gmail',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='image',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='location',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='region',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='resume',
            name='video',
        ),
        migrations.AddField(
            model_name='resume',
            name='resume',
            field=models.FileField(default='g.pdf', upload_to='documents'),
            preserve_default=False,
        ),
    ]
